[[entry]]
difficulty = "hard"
question = "What year did Albrecht Dürer create the painting \"The Young Hare\"?"
correctAnswer = "1502"
incorrectAnswers = [
  "1702",
  "1402",
  "1602",
]

[[entry]]
difficulty = "easy"
question = "Who sculpted the statue of David?"
correctAnswer = "Michelangelo"
incorrectAnswers = [
  "Gian Lorenzo Bernini",
  "Auguste Rodin",
  "Donatello",
]

[[entry]]
difficulty = "easy"
question = "Who painted The Starry Night?"
correctAnswer = "Vincent van Gogh"
incorrectAnswers = [
  "Pablo Picasso",
  "Leonardo da Vinci",
  "Michelangelo",
]

[[entry]]
difficulty = "easy"
question = "Who painted the Sistine Chapel?"
correctAnswer = "Michelangelo"
incorrectAnswers = [
  "Leonardo da Vinci",
  "Pablo Picasso",
  "Raphael",
]

[[entry]]
difficulty = "hard"
question = "What year was the Mona Lisa finished?"
correctAnswer = "1504"
incorrectAnswers = [
  "1487",
  "1523",
  "1511",
]

[[entry]]
difficulty = "medium"
question = "Which time signature is commonly known as “Cut Time?”"
correctAnswer = "2/2"
incorrectAnswers = [
  "4/4",
  "6/8",
  "3/4",
]

[[entry]]
difficulty = "hard"
question = "What French sculptor designed the Statue of Liberty? "
correctAnswer = "Frédéric Auguste Bartholdi"
incorrectAnswers = [
  "Jean-Léon Gérôme",
  "Auguste Rodin",
  "Henri Matisse",
]

[[entry]]
difficulty = "medium"
question = "Which artist’s studio was known as 'The Factory'?"
correctAnswer = "Andy Warhol"
incorrectAnswers = [
  "Roy Lichtenstein",
  "David Hockney",
  "Peter Blake",
]

[[entry]]
difficulty = "medium"
question = "Which one of these paintings is not by Caspar David Friedrich?"
correctAnswer = "The Black Sea"
incorrectAnswers = [
  "The Sea of Ice",
  "Wanderer above the Sea of Fog",
  "The Monk by the Sea",
]

[[entry]]
difficulty = "easy"
question = "Which Van Gogh painting depicts the view from his asylum in Saint-Rémy-de-Provence in southern France?"
correctAnswer = "The Starry Night"
incorrectAnswers = [
  "Wheatfields with Crows",
  "The Sower with Setting Sun",
  "The Church at Auvers",
]

[[entry]]
difficulty = "easy"
question = "What is the name of the Japanese art of folding paper into decorative shapes and figures?"
correctAnswer = "Origami"
incorrectAnswers = [
  "Sumi-e",
  "Ukiyo-e",
  "Haiku",
]

[[entry]]
difficulty = "easy"
question = "Which painting was not made by Vincent Van Gogh?"
correctAnswer = "The Ninth Wave"
incorrectAnswers = [
  "Café Terrace at Night",
  "Bedroom In Arles",
  "Starry Night",
]

[[entry]]
difficulty = "easy"
question = "Who painted \"The Starry Night\"?"
correctAnswer = "Vincent van Gogh"
incorrectAnswers = [
  "Edvard Munch",
  "Pablo Picasso",
  "Claude Monet",
]

[[entry]]
difficulty = "medium"
question = "Which of these are the name of a famous marker brand?"
correctAnswer = "Copic"
incorrectAnswers = [
  "Dopix",
  "Cofix",
  "Marx",
]

[[entry]]
difficulty = "medium"
question = "Who designed the Chupa Chups logo?"
correctAnswer = "Salvador Dali"
incorrectAnswers = [
  "Pablo Picasso",
  "Andy Warhol",
  "Vincent van Gogh",
]

[[entry]]
difficulty = "medium"
question = "Which artist's style was to use small different colored dots to create a picture?"
correctAnswer = "Georges Seurat"
incorrectAnswers = [
  "Paul Cézanne",
  "Vincent Van Gogh",
  "Henri Rousseau",
]

[[entry]]
difficulty = "hard"
question = "How many paint and pastel versions of \"The Scream\" is Norwegian painter Edvard Munch believed to have produced?"
correctAnswer = "4"
incorrectAnswers = [
  "1",
  "3",
  "2",
]

[[entry]]
difficulty = "hard"
question = "The painting \"The Starry Night\" by Vincent van Gogh was part of which art movement?"
correctAnswer = "Post-Impressionism"
incorrectAnswers = [
  "Romanticism",
  "Neoclassical",
  "Impressionism",
]

[[entry]]
difficulty = "hard"
question = "Which of these is not an additional variation of the color purple?"
correctAnswer = "Kobicha"
incorrectAnswers = [
  "Byzantium",
  "Pomp and Power",
  "Palatinate",
]

[[entry]]
difficulty = "easy"
question = "Who painted the biblical fresco The Creation of Adam?"
correctAnswer = "Michelangelo"
incorrectAnswers = [
  "Leonardo da Vinci",
  "Caravaggio",
  "Rembrandt",
]

[[entry]]
difficulty = "easy"
question = "Who painted \"Swans Reflecting Elephants\", \"Sleep\", and \"The Persistence of Memory\"?"
correctAnswer = "Salvador Dali"
incorrectAnswers = [
  "Jackson Pollock",
  "Vincent van Gogh",
  "Edgar Degas",
]

[[entry]]
difficulty = "easy"
question = "Who painted the Mona Lisa?"
correctAnswer = "Leonardo da Vinci"
incorrectAnswers = [
  "Pablo Picasso",
  "Claude Monet",
  "Vincent van Gogh",
]

[[entry]]
difficulty = "hard"
question = "Albrecht Dürer's birthplace and place of death were in..."
correctAnswer = "Nürnberg"
incorrectAnswers = [
  "Augsburg",
  "Bamberg",
  "Berlin",
]

[[entry]]
difficulty = "easy"
question = "Who painted the Mona Lisa?"
correctAnswer = "Leonardo da Vinci "
incorrectAnswers = [
  "Pablo Picasso",
  " Vincent van Gogh",
  "Michelangelo",
]

[[entry]]
difficulty = "hard"
question = "Painter Piet Mondrian (1872 - 1944) was a part of what movement?"
correctAnswer = "Neoplasticism"
incorrectAnswers = [
  "Precisionism",
  "Cubism",
  "Impressionism",
]

[[entry]]
difficulty = "medium"
question = "What nationality was the surrealist painter Salvador Dali?"
correctAnswer = "Spanish"
incorrectAnswers = [
  "Italian",
  "French",
  "Portuguese",
]

[[entry]]
difficulty = "medium"
question = "Who painted the epic mural Guernica?"
correctAnswer = "Pablo Picasso"
incorrectAnswers = [
  "Francisco Goya",
  "Leonardo da Vinci",
  "Henri Matisse",
]
