[[entry]]
difficulty = "medium"
question = "How many zeros are there in a googol?"
correctAnswer = "100"
incorrectAnswers = [
  "10",
  "1,000",
  "1,000,000",
]

[[entry]]
difficulty = "medium"
question = "Which of the following dice is not a platonic solid?"
correctAnswer = "10-sided die"
incorrectAnswers = [
  "12-sided die",
  "20-sided die",
  "8-sided die",
]

[[entry]]
difficulty = "medium"
question = "What is the alphanumeric representation of the imaginary number?"
correctAnswer = "i"
incorrectAnswers = [
  "e",
  "n",
  "x",
]

[[entry]]
difficulty = "hard"
question = "The French mathematician Évariste Galois is primarily known for his work in which?"
correctAnswer = "Galois Theory"
incorrectAnswers = [
  "Galois' Continued Fractions",
  "Galois' Method for PDE's ",
  "Abelian Integration",
]

[[entry]]
difficulty = "medium"
question = "Which greek mathematician ran through the streets of Syracuse naked while shouting \"Eureka\" after discovering the principle of displacement?"
correctAnswer = "Archimedes"
incorrectAnswers = [
  "Euclid",
  "Homer",
  "Eratosthenes",
]

[[entry]]
difficulty = "easy"
question = "What prime number comes next after 19?"
correctAnswer = "23"
incorrectAnswers = [
  "25",
  "21",
  "27",
]

[[entry]]
difficulty = "medium"
question = "What are the first 6 digits of the number \"Pi\"?"
correctAnswer = "3.14159"
incorrectAnswers = [
  "3.14169",
  "3.12423",
  "3.25812",
]

[[entry]]
difficulty = "hard"
question = "How many zeptometres are inside one femtometre?"
correctAnswer = "1,000,000"
incorrectAnswers = [
  "10",
  "1,000,000,000",
  "1000",
]

[[entry]]
difficulty = "easy"
question = "In Roman Numerals, what does XL equate to?"
correctAnswer = "40"
incorrectAnswers = [
  "60",
  "15",
  "90",
]

[[entry]]
difficulty = "hard"
question = "What is the fourth digit of π?"
correctAnswer = "1"
incorrectAnswers = [
  "2",
  "3",
  "4",
]

[[entry]]
difficulty = "medium"
question = "In the complex plane, multiplying a given function by i rotates it anti-clockwise by how many degrees?"
correctAnswer = "90"
incorrectAnswers = [
  "180",
  "270",
  "0",
]

[[entry]]
difficulty = "easy"
question = "The metric prefix \"atto-\" makes a measurement how much smaller than the base unit?"
correctAnswer = "One Quintillionth"
incorrectAnswers = [
  "One Billionth",
  "One Quadrillionth",
  "One Septillionth",
]

[[entry]]
difficulty = "hard"
question = "Which of these numbers is closest to the total number of possible states for an army standard Enigma Machine?"
correctAnswer = "1.58 x 10^20"
incorrectAnswers = [
  "1.58 x 10^22",
  "1.58 x  10^18",
  "1.58 x 10^24",
]

[[entry]]
difficulty = "medium"
question = "What Greek letter is used to signify summation?"
correctAnswer = "Sigma"
incorrectAnswers = [
  "Delta",
  "Alpha",
  "Omega",
]

[[entry]]
difficulty = "medium"
question = "What is the area of a circle with a diameter of 20 inches if π= 3.1415?"
correctAnswer = "314.15 Inches"
incorrectAnswers = [
  "380.1215 Inches",
  "3141.5 Inches",
  "1256.6 Inches",
]

[[entry]]
difficulty = "hard"
question = "The decimal number 31 in hexadecimal would be what?"
correctAnswer = "1F"
incorrectAnswers = [
  "3D",
  "2E",
  "1B",
]

[[entry]]
difficulty = "medium"
question = "What shape does sin(x) or cos(x) make on a graph?"
correctAnswer = "Waves"
incorrectAnswers = [
  "A Parabola",
  "A Straight Line",
  "Zig-Zags",
]

[[entry]]
difficulty = "easy"
question = "What is the correct order of operations for solving equations?"
correctAnswer = "Parentheses, Exponents, Multiplication, Division, Addition, Subtraction"
incorrectAnswers = [
  "Addition, Multiplication, Division, Subtraction, Addition, Parentheses",
  "Parentheses, Exponents, Addition, Substraction, Multiplication, Division",
  "The order in which the operations are written.",
]

[[entry]]
difficulty = "easy"
question = "How many sides does a trapezium have?"
correctAnswer = "4"
incorrectAnswers = [
  "3",
  "5",
  "6",
]

[[entry]]
difficulty = "medium"
question = "What is the Roman numeral for 500?"
correctAnswer = "D"
incorrectAnswers = [
  "L",
  "C",
  "X",
]

[[entry]]
difficulty = "hard"
question = "How many Millibars (mbar) to 1 Inch of Mercury (inHg)"
correctAnswer = "33.9"
incorrectAnswers = [
  "30.0",
  "27.4",
  "10.6",
]

[[entry]]
difficulty = "hard"
question = "What is the plane curve proposed by Descartes to challenge Fermat's extremum-finding techniques called?"
correctAnswer = "Folium of Descartes"
incorrectAnswers = [
  "Elliptic Paraboloid of Descartes",
  "Cartesian Coordinates",
  "Descarte's Helicoid",
]

[[entry]]
difficulty = "hard"
question = "What is the derivative of Acceleration with respect to time?"
correctAnswer = "Jerk"
incorrectAnswers = [
  "Shift",
  "Bump",
  "Slide",
]

[[entry]]
difficulty = "hard"
question = "What is the smallest number that can be expressed as the sum of two positive cubes in two different ways?"
correctAnswer = "1729"
incorrectAnswers = [
  "91",
  "561",
  "4104",
]

[[entry]]
difficulty = "medium"
question = "Which mathematician refused the Fields Medal?"
correctAnswer = "Grigori Perelman"
incorrectAnswers = [
  "Andrew Wiles",
  "Terence Tao",
  "Edward Witten",
]

[[entry]]
difficulty = "easy"
question = "What's the square root of 49?"
correctAnswer = "7"
incorrectAnswers = [
  "4",
  "12",
  "9",
]

[[entry]]
difficulty = "medium"
question = "To the nearest whole number, how many radians are in a whole circle?"
correctAnswer = "6"
incorrectAnswers = [
  "3",
  "4",
  "5",
]

[[entry]]
difficulty = "medium"
question = "In the hexadecimal system, what number comes after 9?"
correctAnswer = "The Letter A"
incorrectAnswers = [
  "10",
  "The Number 0",
  "16",
]

[[entry]]
difficulty = "medium"
question = "What type of function is x²+2x+1?"
correctAnswer = "Quadratic"
incorrectAnswers = [
  "Rational",
  "Linear",
  "Exponential",
]

[[entry]]
difficulty = "hard"
question = "What is the approximate value of mathematical constant e?"
correctAnswer = "2.72"
incorrectAnswers = [
  "3.14",
  "1.62",
  "1.41",
]

[[entry]]
difficulty = "medium"
question = "What is the first Mersenne prime exponent over 1000?"
correctAnswer = "1279"
incorrectAnswers = [
  "2203",
  "1009",
  "1069",
]

[[entry]]
difficulty = "easy"
question = "What is the symbol for Displacement?"
correctAnswer = "Δr"
incorrectAnswers = [
  "dr",
  "Dp",
  "r",
]

[[entry]]
difficulty = "hard"
question = "The notion of a \"set that contains all sets which do not contain themselves\" is a paradoxical idea attributed to which English philosopher?"
correctAnswer = "Bertrand Russel"
incorrectAnswers = [
  "Francis Bacon",
  "John Locke",
  "Alfred North Whitehead",
]

[[entry]]
difficulty = "hard"
question = "Which of the following mathematicians made major contributions to game theory?"
correctAnswer = "John Von Neumann"
incorrectAnswers = [
  "Carl Friedrich Gauss",
  "Leonhard Euler",
  "Stefan Banach",
]

[[entry]]
difficulty = "medium"
question = "How many books are in Euclid's Elements of Geometry?"
correctAnswer = "13"
incorrectAnswers = [
  "8",
  "10",
  "17",
]

[[entry]]
difficulty = "hard"
question = "Which of the following famous mathematicians died in a duel at the age of 20?"
correctAnswer = "Galois"
incorrectAnswers = [
  "Abel",
  "Euler",
  "Gauss",
]

[[entry]]
difficulty = "easy"
question = "How many sides does a heptagon have?"
correctAnswer = "7"
incorrectAnswers = [
  "8",
  "6",
  "5",
]
